name: PR Validation

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  create_runner:
   uses: ./.github/workflows/create_runner.yaml
   secrets: inherit
   with:
     runner_name: weather-app-runner
     github_org_name: Locally-build
