name: PR Validation

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  create_runner:
   uses: ./.github/workflows/create_runner.yaml
   secrets: inherit
   with:
     REGION: us-east-2
     KEY_NAME: ${{ secrets.KEY_NAME }}
     TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
     TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     TF_VAR_aws_region: "us-east-2"
     TF_VAR_aws_ami_id: "ami-09b2201fa15c4cb83"
     TF_VAR_aws_availability_zone_index: 1
     TF_VAR_use_intel: false
     TF_VAR_use_m2_pro: false
     TF_VAR_host_count: 1
     TF_VAR_host_base_name: "builder"
     TF_VAR_parallels_key: ${{ secrets.PARALLELS_KEY }}