name: PR Validation

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  create_runner:
    name: Create Self Hosted Runners
    uses: ./.github/workflows/deploy_runner.yaml
    secrets: inherit
    with:
      runner_name: weather-app-runner
      github_org_name: Locally-build/acme-weather-app
  build_ios:
    name: Build iOS
    uses: ./.github/workflows/build_ios.yaml
    with:
      region: us-east-2
